spring:
  profiles:
    active: dev
  application:
    name: pic-saver-core

server:
  port: 8081
#management.endpoints.web.exposure.include=*

#bot设置
bot:
  qq: 1600699908
  authKey: miraiAuthKey

#log设置
logging:
  level:
    root: info
    top:
      cookizi: info
