bot:
  apiUrl: http://192.168.50.30:8080/
  wsUrl: ws://192.168.50.30:8080/message
#  savePath: D:\
  savePath: /botData/
  forwardGroups:
  proxy-host: 192.168.50.30
  proxy-port: 10809
  mirai-http-api-path:
  proxy: false
  jobWhiteGroup:
  setuRate: 50

task:
  executor:
    core-pool-size: 80
    max-pool-size: 200
    thread-name-prefix: taskExecutor-
  scheduler:
    pool-size: 80
    thread-name-prefix: taskScheduler-